[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cliff_only_vesting_contract = "J3Qo8zJpx3cj6PW8Zru1xTbR2WFPLmy8rJMyoctKNiVf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --import=tsx -p ./tsconfig.json -t 1000000 tests/**/*.ts"